# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gratuit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for gratuit
  pod 'AlamofireImage'
  pod 'Parse'

  target 'gratuit' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'gratuitUITests' do
    # Pods for testing
  end

end
